import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { Box, Button } from '@mui/material';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inventory Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Navigation Bar */}
        <Box sx={{
          padding: 2,
          backgroundColor: '#1976d2',
          color: '#fff',
          display: 'flex',
          justifyContent: 'center'
        }}>
          <Link href="/sign-up" passHref>
            <Button color="inherit" sx={{ marginRight: 2 }}>Sign Up</Button>
          </Link>
          <Link href="/sign-in" passHref>
            <Button color="inherit" sx={{ marginRight: 2 }}>Sign In</Button>
          </Link>
          <Link href="/home" passHref>
            <Button color="inherit">Home</Button>
          </Link>
        </Box>

        {/* Page Content */}
        {children}
      </body>
    </html>
  );
}
